"""init_all_tables

Revision ID: 551226eecc95
Revises: 
Create Date: 2026-02-28 15:42:41.853023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551226eecc95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('center_code', sa.String(length=20), nullable=True),
    sa.Column('name_initials', sa.String(length=10), nullable=True),
    sa.Column('full_name_encrypted', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('visit_number', sa.String(length=50), nullable=True),
    sa.Column('employment_status', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.Integer(), nullable=True),
    sa.Column('insurance_coverage', sa.Integer(), nullable=True),
    sa.Column('smoking_status', sa.Integer(), nullable=True),
    sa.Column('smoking_per_day', sa.Integer(), nullable=True),
    sa.Column('drinking_status', sa.Integer(), nullable=True),
    sa.Column('drinking_per_day', sa.Integer(), nullable=True),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('enrolled', 'withdrawn', 'completed'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('researcher', 'qc', 'admin'), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('subject_signed_date', sa.Date(), nullable=True),
    sa.Column('subject_contact', sa.String(length=50), nullable=True),
    sa.Column('proxy_name', sa.String(length=100), nullable=True),
    sa.Column('proxy_signed_date', sa.Date(), nullable=True),
    sa.Column('proxy_contact', sa.String(length=50), nullable=True),
    sa.Column('witness_name', sa.String(length=100), nullable=True),
    sa.Column('witness_signed_date', sa.Date(), nullable=True),
    sa.Column('witness_contact', sa.String(length=50), nullable=True),
    sa.Column('investigator_name', sa.String(length=100), nullable=True),
    sa.Column('investigator_signed_date', sa.Date(), nullable=True),
    sa.Column('investigator_contact', sa.String(length=50), nullable=True),
    sa.Column('scan_file_path', sa.String(length=500), nullable=True),
    sa.Column('scan_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.Enum('baseline', 'M6', 'M12', 'M18', 'M24'), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'signed', 'locked'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_table('comorbidities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Integer(), nullable=True),
    sa.Column('hypertension_date', sa.String(length=20), nullable=True),
    sa.Column('ckd', sa.Integer(), nullable=True),
    sa.Column('ckd_date', sa.String(length=20), nullable=True),
    sa.Column('chd', sa.Integer(), nullable=True),
    sa.Column('chd_date', sa.String(length=20), nullable=True),
    sa.Column('angina', sa.Integer(), nullable=True),
    sa.Column('angina_date', sa.String(length=20), nullable=True),
    sa.Column('mi', sa.Integer(), nullable=True),
    sa.Column('mi_date', sa.String(length=20), nullable=True),
    sa.Column('stroke', sa.Integer(), nullable=True),
    sa.Column('stroke_date', sa.String(length=20), nullable=True),
    sa.Column('dr', sa.Integer(), nullable=True),
    sa.Column('dr_date', sa.String(length=20), nullable=True),
    sa.Column('dr_macular', sa.Boolean(), nullable=True),
    sa.Column('dr_non_proliferative', sa.Boolean(), nullable=True),
    sa.Column('dr_proliferative', sa.Boolean(), nullable=True),
    sa.Column('dn', sa.Integer(), nullable=True),
    sa.Column('dn_date', sa.String(length=20), nullable=True),
    sa.Column('dn_peripheral', sa.Boolean(), nullable=True),
    sa.Column('dn_autonomic', sa.Boolean(), nullable=True),
    sa.Column('df', sa.Integer(), nullable=True),
    sa.Column('df_date', sa.String(length=20), nullable=True),
    sa.Column('df_healed_ulcer', sa.Boolean(), nullable=True),
    sa.Column('df_active_ulcer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('cost_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('drug_cost', sa.Float(), nullable=True),
    sa.Column('lab_cost', sa.Float(), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=True),
    sa.Column('supply_cost', sa.Float(), nullable=True),
    sa.Column('other_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('fasting_glucose', sa.Float(), nullable=True),
    sa.Column('hba1c', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.Column('tg', sa.Float(), nullable=True),
    sa.Column('hdl_c', sa.Float(), nullable=True),
    sa.Column('ldl_c', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('scr', sa.Float(), nullable=True),
    sa.Column('egfr', sa.Float(), nullable=True),
    sa.Column('ua', sa.Float(), nullable=True),
    sa.Column('bun', sa.Float(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('lifestyle_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('diet_scores_json', sa.Text(), nullable=True),
    sa.Column('diet_total', sa.Float(), nullable=True),
    sa.Column('diet_level', sa.String(length=20), nullable=True),
    sa.Column('exercise_scores_json', sa.Text(), nullable=True),
    sa.Column('exercise_total', sa.Float(), nullable=True),
    sa.Column('exercise_level', sa.String(length=20), nullable=True),
    sa.Column('bad_habits', sa.String(length=200), nullable=True),
    sa.Column('meal_basic_info_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('meal_time', sa.String(length=20), nullable=True),
    sa.Column('dish_name', sa.String(length=100), nullable=True),
    sa.Column('ingredients', sa.String(length=200), nullable=True),
    sa.Column('raw_cooked', sa.String(length=10), nullable=True),
    sa.Column('estimated_amount', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type', sa.String(length=50), nullable=True),
    sa.Column('drug_name', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=30), nullable=True),
    sa.Column('dose', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('sbp_mmhg', sa.Integer(), nullable=True),
    sa.Column('dbp_mmhg', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_type', sa.String(length=20), nullable=False),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Integer(), nullable=True),
    sa.Column('q3', sa.Integer(), nullable=True),
    sa.Column('q4', sa.Integer(), nullable=True),
    sa.Column('q5', sa.Integer(), nullable=True),
    sa.Column('q6', sa.Integer(), nullable=True),
    sa.Column('q7', sa.Integer(), nullable=True),
    sa.Column('q8', sa.Integer(), nullable=True),
    sa.Column('q9', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('eq_mobility', sa.Integer(), nullable=True),
    sa.Column('eq_self_care', sa.Integer(), nullable=True),
    sa.Column('eq_usual_activity', sa.Integer(), nullable=True),
    sa.Column('eq_pain', sa.Integer(), nullable=True),
    sa.Column('eq_anxiety', sa.Integer(), nullable=True),
    sa.Column('eq_vas_score', sa.Integer(), nullable=True),
    sa.Column('dtsq_open_text', sa.Text(), nullable=True),
    sa.Column('phq9_symptoms', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaires')
    op.drop_table('physical_exams')
    op.drop_table('medications')
    op.drop_table('meal_records')
    op.drop_table('lifestyle_assessments')
    op.drop_table('lab_results')
    op.drop_table('cost_indicators')
    op.drop_table('comorbidities')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
