"""phase0 fields + AE

Revision ID: cfe8511db131
Revises: bf3c5b0e2c49
Create Date: 2026-09-11 18:01:32.798060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe8511db131'
down_revision: Union[str, None] = 'bf3c5b0e2c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe'), nullable=True),
    sa.Column('is_serious', sa.Boolean(), nullable=True),
    sa.Column('relation', sa.Enum('definite', 'probable', 'possible', 'unlikely', 'unrelated'), nullable=True),
    sa.Column('outcome', sa.Enum('recovered', 'recovering', 'not_recovered', 'death', 'unknown'), nullable=True),
    sa.Column('action_taken', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverse_events_id'), 'adverse_events', ['id'], unique=False)
    op.add_column('consent_records', sa.Column('consent_version', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('id_card_encrypted', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('marital_status', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('withdraw_reason', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('withdraw_date', sa.Date(), nullable=True))
    # status 枚举扩为 enrolled/completed/dropout/withdrawn（autogenerate 无法检测枚举值变化，手写）
    op.alter_column(
        'patients', 'status',
        existing_type=sa.Enum('enrolled', 'withdrawn', 'completed'),
        type_=sa.Enum('enrolled', 'completed', 'dropout', 'withdrawn'),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'withdraw_date')
    op.drop_column('patients', 'withdraw_reason')
    op.drop_column('patients', 'marital_status')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'id_card_encrypted')
    op.drop_column('consent_records', 'consent_version')
    op.drop_index(op.f('ix_adverse_events_id'), table_name='adverse_events')
    op.drop_table('adverse_events')
    # ### end Alembic commands ###
